Description: Pipeline for ecr-images
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      ManagedPolicyArns:
        - !ImportValue core-infrastructure-global-codebuild-base-policy-arn
      Policies:
        - PolicyName: ecr-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                Resource: "*"
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !ImportValue core-infrastructure-eu-west-1-build-artifacts-bucket
        Path: /artifacts/ecr-images/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Name: ecr-images-build
      TimeoutInMinutes: 10
      BuildBatchConfig:
        CombineArtifacts: false
        TimeoutInMins: 15
        ServiceRole: !Ref CodeBuildRole
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !ImportValue core-infrastructure-eu-west-1-build-artifacts-bucket
      Name: ecr-images
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue core-infrastructure-global-codepipeline-base-role-arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Namespace: SourceVariables
              Configuration:
                ConnectionArn: !ImportValue core-infrastructure-eu-west-1-codestar-github-connection-arn
                FullRepositoryId: alexchesters/ecr-images
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
        - Name: Deploy-CloudFormation
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Update-Stack
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: ecr-images
                RoleArn: !ImportValue core-infrastructure-global-codepipeline-cloudformation-role-arn
                TemplatePath: GitHubSource::stacks/infrastructure.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/infrastructure.json
        - Name: Build-Images
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Build
              Configuration:
                BatchEnabled: true
                ProjectName: !Ref CodeBuildProject
